### ISSUE TITLE
Errors since pf1 update

### ISSUE THREAD

**Issue by folken88** [acd-jake/acd-talking-actors#45] opened 2024-08-25 19:30 UTC
"/talk is not a valid chat message command" since the update.

I turned off all other mods so it is just foundry v11, pf1 10.7, and talking actors .8

Console says:
TypeError: Cannot read properties of undefined (reading 'OOC')
    at ElevenlabsConnector.postToChat (ElevenlabsConnector.js:212:45)
    at ElevenlabsConnector.processChatMessage (ElevenlabsConnector.js:135:43)
    at Object.fn (init.js:128:41)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at ChatLog.processMessage (foundry.js:85912:16)
    at ChatLog._onChatKeyDown (foundry.js:86228:19)
    at HTMLTextAreaElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
onError @ foundry.js:753
#call @ foundry.js:734
call @ foundry.js:712
processMessage @ foundry.js:85912
_onChatKeyDown @ foundry.js:86228
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
foundry.js:68326 Error: /talk is not a valid chat message command.
    at ChatLog.processMessage (foundry.js:85918:40)
    at ChatLog._onChatKeyDown (foundry.js:86228:19)
    at HTMLTextAreaElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
fetch @ foundry.js:68326
notify @ foundry.js:68223
error @ foundry.js:68260
(anonymous) @ foundry.js:86232
Promise.catch (async)
_onChatKeyDown @ foundry.js:86231
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
foundry.js:85918 Uncaught (in promise) Error: /talk is not a valid chat message command.
    at ChatLog.processMessage (foundry.js:85918:40)
    at ChatLog._onChatKeyDown (foundry.js:86228:19)
    at HTMLTextAreaElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
processMessage @ foundry.js:85918
_onChatKeyDown @ foundry.js:86228
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
Promise.catch (async)
_onChatKeyDown @ foundry.js:86231
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

**Comment by folken88** [comment] 2024-09-01 01:23
If there's anything we can do to help, we'd love to! We love the mod and use it all the time. We try to have sounds for everything in our game for our blind players and pf1 + talking actors has made a great combination!

**Comment by acd-jake** [comment] 2024-09-01 08:27
Hi, thank you for the offer - I think I already have a solution.

As you have already recognized, the problem is due to an incompatibility between Foundry generations 11 and 12.

I have now added a workaround that will be released with module version 0.8.1. Would you try it with Fondry version 11?

I'm glad you find the module useful and enjoy using it. If you have any suggestions for further improvements or requests for handling or new functions, please let me know.

**Closed** 2024-09-01 08:30 UTC
Labels: bug
